# Generated by Django 3.2 on 2021-12-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('food', models.CharField(max_length=100, verbose_name='Alimentação')),
                ('life_estimate', models.IntegerField(verbose_name='Expectativa de Vida')),
                ('animal_category', models.CharField(choices=[('INVERTEBRATES', 'Invertebrados'), ('FISH', 'Peixe'), ('AMPHIBIANS', 'Anfíbios'), ('REPTILES', 'Répteis'), ('BIRDS', 'Aves'), ('MAMMALS', 'Mamíferos')], max_length=20, verbose_name='Animal Categoria')),
                ('animal_age', models.CharField(choices=[('Dias', 'Dias'), ('Meses', 'Meses'), ('Anos', 'Anos')], max_length=6)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
    ]
