# Generated by Django 3.2 on 2021-12-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias_animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_category',
            field=models.CharField(choices=[('Invertebrados', 'Invertebrados'), ('FISH', 'Peixe'), ('Anfíbios', 'Anfíbios'), ('Répteis', 'Répteis'), ('Aves', 'Aves'), ('Mamíferos', 'Mamíferos')], max_length=20, verbose_name='Animal Categoria'),
        ),
    ]
